spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amigo
    username: "postgres"
    password: "Madik2157"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

